language: go
sudo: false

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.11
  - tip

before_install:
  - go get -t -v ./...

script:
 - go vet $(go list ./... | grep -v /vendor/)
 - go test -race -coverprofile=coverage.txt -covermode=atomic github.com/breathbath/gotainer_gen/container

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
